name: "Terraform GCP Infrastructure"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GOOGLE_PROJECT: tonal-transit-452819-t1
      GOOGLE_REGION: europe-central2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tonal-transit-452819-t1
          install_components: 'beta'

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Verify GCP Authentication
        run: gcloud auth list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt
        continue-on-error: true 

      - name: Cache Terraform Plugins & Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            environments/dev/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Initialize Terraform (Dev)
        run: terraform init -upgrade
        working-directory: environments/dev

      - name: Terraform Plan (Dev)
        run: terraform plan -no-color -var "project_id=${GOOGLE_PROJECT}" -var "region=${GOOGLE_REGION}" -var "ssh_pub_key=${{ secrets.SSH_PUBLIC_KEY }}" -var "ssh_user=ubuntu" -var "grafana_admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" -var "domain_name=example.com"
        working-directory: environments/dev
        timeout-minutes: 10

      - name: Check Runner Resources
        run: free -m && df -h

      - name: Terraform Apply (Dev)
        run: terraform apply -auto-approve -var "project_id=${GOOGLE_PROJECT}" -var "region=${GOOGLE_REGION}" -var "ssh_pub_key=${{ secrets.SSH_PUBLIC_KEY }}" -var "ssh_user=ubuntu" -var "grafana_admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" -var "domain_name=example.com"
        working-directory: environments/dev
        timeout-minutes: 20